# Generated by Django 6.0.5 on 2026-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_seed_demo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
